### ISSUE TITLE
Better instruction for how to clone the git repository

### ISSUE THREAD

**Issue by JohnPyleWork** [nhsalpha/nhs_prototype_kit#190]
Hi
The instructions from https://github.com/nhsalpha/nhs_prototype_kit
say:

git clone git@github.com:/nhsalpha/nhs_prototype_kit.git

When I do that I get (amongst other messages):
_Permission denied (publickey).
fatal: Could not read from remote repository._

But If I do this
git clone https://github.com/nhsalpha/nhs_prototype_kit.git

All seems to be fine.

Maybe you could update the page. I'm no expert, but it might help others.

**Comment by fawkesley** [comment]
Thanks for the feedback @JohnPyleWork. I've made a pull request to improve this: #191
