### ISSUE TITLE
consider using hashes instead of functions

### ISSUE THREAD

**Issue by joelanman** [nhsalpha/nhs_prototype_kit#64]
feel free to totally ignore this, I just noticed you're using a function pattern to look up data:

```
function practice_details_for_slug(slug) {
  switch(slug) {
    case 'lakeside-surgery':
      return {
        name: 'Lakeside Surgery',
        address: '22 Castelnau, London, NW13 9HJ'
      };
    case 'shrewsbottom-surgery':
      return {
        name: 'Shrewsbottom Surgery',
        address: '15 Pound Lane, London, NW12 9AT'
      };
    case 'victoria-medical-centre':
      return {
        name: 'Victoria Medical Centre',
        address: '48 Buttoy, London, NW13 9HT'
      };
  }
}
```

I normally use a hash for this:

```
practiceDetails =  {
    'lakeside-surgery': {
        name: 'Lakeside Surgery',
        address: '22 Castelnau, London, NW13 9HJ'
    },
    'shrewsbottom-surgery': {
        name: 'Shrewsbottom Surgery',
        address: '15 Pound Lane, London, NW12 9AT'
    },
    'victoria-medical-centre': {
        name: 'Victoria Medical Centre',
        address: '48 Buttoy, London, NW13 9HT'
    }
}

```

and then called:

```
var selectedPracticeDetails = practiceDetails[slug];
```

you can even put this data in a separate JSON file and load it using `require`

**Comment by evilstreak** [comment]
Good suggestion, thanks!

It feels like we're on the edge of wanting to make the templates more data driven rather than being flat hard coded pages, and moving the data into JSON files will make it easier to handle.

**Comment by joelanman** [comment]
cool yeh I should really add this to the docs.

one important note - using `require` to load JSON is really quick and simple, but node caches the result. If you don't want that behaviour use `fs.readFileSync` and `JSON.parse` instead.

**Comment by evilstreak** [comment]
We've pulled out most of the data into JSON files: https://github.com/nhsalpha/nhs_prototype_kit/tree/master/db

We're doing the rest now, at least for the bits we're actively working on.
